blueprint:
  name: Notificación entrada salida de zona
  description: Envía una notificación cuando una persona entra o sale de una zona específica.
  domain: automation
  source_url: https://github.com/home-assistant/core/blob/dev/homeassistant/components/automation/blueprints/notify_leaving_zone.yaml
  author: Home Assistant (modificado en español)
  input:
    person_entity:
      name: Persona
      selector:
        entity:
          filter:
            domain: person
    zone_entity:
      name: Zona
      selector:
        entity:
          filter:
            domain: zone
    notify_device:
      name: Dispositivo a notificar
      description: El dispositivo debe tener instalada la app oficial de Home Assistant.
      selector:
        device:
          filter:
            integration: mobile_app

trigger:
  platform: state
  entity_id: !input person_entity

variables:
  zone_entity: !input zone_entity
  zone_state: "{{ states[zone_entity].name }}"
  person_entity: !input person_entity
  person_name: "{{ states[person_entity].name }}"

action:
  - choose:
      - conditions:
          - condition: template
            value_template: >
              {{ (zone_entity == 'zone.home' and trigger.from_state.state == 'home' and trigger.to_state.state != 'home') or
                 (trigger.from_state.state == zone_state and trigger.to_state.state != zone_state) }}
        sequence:
          - alias: "Notificar que la persona ha salido de la zona"
            domain: mobile_app
            type: notify
            device_id: !input notify_device
            message: "{{ person_name }} ha salido de {{ zone_state }}"
      - conditions:
          - condition: template
            value_template: >
              {{ (zone_entity == 'zone.home' and trigger.from_state.state != 'home' and trigger.to_state.state == 'home') or
                 (trigger.from_state.state != zone_state and trigger.to_state.state == zone_state) }}
        sequence:
          - alias: "Notificar que la persona ha entrado en la zona"
            domain: mobile_app
            type: notify
            device_id: !input notify_device
            message: "{{ person_name }} ha entrado en {{ zone_state }}"

